runtime: nodejs16  # Choose the Node.js runtime version you want to use

env_variables:
  NODE_ENV: production  # Set your Node.js environment to production
  MONGO_DB_URL: 'mongodb://127.0.0.1:27017/phuc_long'
  ACCESS_TOKEN_PRIVATE_KEY: 'accesstokenkey'
  REFRESH_TOKEN_PRIVATE_KEY: 'refreshtokenkey'
  ACCESS_TOKEN_EXPIRATION: "1h"  
  REFRESH_TOKEN_EXPIRATION: "30d"
  CLIENT_ID: 'Aa1bokVLVxRR8d3Rw95Hq6ETrsmDPTOYSocPEmh9sj2HsRj1cRvAJCSBQ_uWeQbJqVHK09v1lXMPI5KF'
  SALT: 10
  EMAIL: 'tailx0913@gmail.com'
  EMAIL_PASSWORD: 'pquo jnnn hkob gygf'
  HOST_NAME: 'http://localhost:3001'
  STRIPE_SECRET_KEY: 'sk_test_51L3WQIKptgKXepUNM36u8sKy0MAQYXWHQlsAbBGpQ6v4r9pWQVgc7tHycVkbvnYuJD3VtHlNn3JjtneAlerNV4kc00D7mGRZO6'

handlers:
- url: /.*
  script: auto